### ISSUE TITLE
unable to run the demo

### ISSUE THREAD

**Issue by Hannibal046** [jayelm/gisting#16]
First off, thank you for the excellent work on this project.

I'm experiencing an issue while attempting to run the demo. I've combed through the existing repository issues but have not found a solution that addresses my problem.

Here's the procedure I've followed:
Install the required environment with:
```
conda create -n gist python=3.9 && conda activate gist
pip install torch
pip install -r requirements.txt
```
And I got the following installed packages:
```
Package                  Version
------------------------ ------------
absl-py                  2.0.0
accelerate               0.18.0
aiohttp                  3.8.6
aiosignal                1.3.1
annotated-types          0.6.0
antlr4-python3-runtime   4.9.3
async-timeout            4.0.3
attrs                    23.1.0
certifi                  2023.7.22
charset-normalizer       3.3.2
click                    8.1.7
cmake                    3.27.7
datasets                 2.10.0
deepspeed                0.8.3
dill                     0.3.6
docker-pycreds           0.4.0
evaluate                 0.3.0
filelock                 3.13.1
fire                     0.5.0
frozenlist               1.4.0
fsspec                   2023.10.0
gitdb                    4.0.11
GitPython                3.1.40
hjson                    3.1.0
huggingface-hub          0.18.0
hydra-core               1.2.0
idna                     3.4
Jinja2                   3.1.2
joblib                   1.3.2
lit                      17.0.4
MarkupSafe               2.1.3
mpmath                   1.3.0
multidict                6.0.4
multiprocess             0.70.14
networkx                 3.2.1
ninja                    1.11.1.1
nltk                     3.6.2
numpy                    1.21.2
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.2.10.91
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusparse-cu11     11.7.4.91
nvidia-nccl-cu11         2.14.3
nvidia-nvtx-cu11         11.7.91
omegaconf                2.3.0
openai                   0.27.2
packaging                23.2
pandas                   2.0.3
pathtools                0.1.2
pip                      23.3
promise                  2.3
protobuf                 4.25.0
psutil                   5.9.6
py-cpuinfo               9.0.0
pyarrow                  14.0.0
pydantic                 2.4.2
pydantic_core            2.10.1
python-dateutil          2.8.2
pytz                     2023.3.post1
PyYAML                   6.0.1
regex                    2023.10.3
requests                 2.31.0
responses                0.18.0
rouge-score              0.1.2
sentencepiece            0.1.98
sentry-sdk               1.34.0
setproctitle             1.3.3
setuptools               68.0.0
shortuuid                1.0.11
six                      1.16.0
smmap                    5.0.1
sympy                    1.12
termcolor                2.3.0
tokenizers               0.13.3
torch                    2.0.0
tqdm                     4.66.1
transformers             4.28.0.dev0
triton                   2.0.0
typing_extensions        4.8.0
tzdata                   2023.3
urllib3                  2.0.7
wandb                    0.13.4
wheel                    0.41.2
xxhash                   3.4.1
yarl                     1.9.2
```

After this, I use the this command to run the demo 
```
python -m src.compress --model_name_or_path jayelm/llama-7b-gist-1 --base_llama_path llama-7b \
    --instruction "Name the top cities in France that should not be missed. Include the best aspects of each place as well."
```
But I encountered the following problem:
```
/anaconda/envs/gist/lib/python3.9/site-packages/pydantic/_internal/_config.py:317: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
* 'validate_all' has been renamed to 'validate_default'
  warnings.warn(message, UserWarning)
/anaconda/envs/gist/lib/python3.9/site-packages/pydantic/_internal/_fields.py:128: UserWarning: Field "model_persistence_threshold" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/anaconda/envs/gist/lib/python3.9/site-packages/pydantic/_internal/_config.py:317: UserWarning: Valid config keys have changed in V2:
* 'validate_all' has been renamed to 'validate_default'
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "/anaconda/envs/gist/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1126, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/anaconda/envs/gist/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/anaconda/envs/gist/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 34, in <module>
    from ...modeling_utils import PreTrainedModel
  File "/anaconda/envs/gist/lib/python3.9/site-packages/transformers/modeling_utils.py", line 37, in <module>
    from .deepspeed import deepspeed_config, is_deepspeed_zero3_enabled
  File "/anaconda/envs/gist/lib/python3.9/site-packages/transformers/deepspeed.py", line 38, in <module>
    from accelerate.utils.deepspeed import HfDeepSpeedConfig as DeepSpeedConfig
  File "/anaconda/envs/gist/lib/python3.9/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/anaconda/envs/gist/lib/python3.9/site-packages/accelerate/accelerator.py", line 31, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/anaconda/envs/gist/lib/python3.9/site-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/anaconda/envs/gist/lib/python3.9/site-packages/accelerate/utils/__init__.py", line 106, in <module>
    from .launch import (
  File "/anaconda/envs/gist/lib/python3.9/site-packages/accelerate/utils/launch.py", line 28, in <module>
    from ..utils.other import merge_dicts
  File "/anaconda/envs/gist/lib/python3.9/site-packages/accelerate/utils/other.py", line 28, in <module>
    from deepspeed import DeepSpeedEngine
  File "/anaconda/envs/gist/lib/python3.9/site-packages/deepspeed/__init__.py", line 15, in <module>
    from . import module_inject
  File "/anaconda/envs/gist/lib/python3.9/site-packages/deepspeed/module_inject/__init__.py", line 3, in <module>
    from .replace_module import replace_transformer_layer, revert_transformer_layer, ReplaceWithTensorSlicing, GroupQuantizer, generic_injection
  File "/anaconda/envs/gist/lib/python3.9/site-packages/deepspeed/module_inject/replace_module.py", line 803, in <module>
    from ..pipe import PipelineModule
  File "/anaconda/envs/gist/lib/python3.9/site-packages/deepspeed/pipe/__init__.py", line 3, in <module>
    from ..runtime.pipe import PipelineModule, LayerSpec, TiedLayerSpec
  File "/anaconda/envs/gist/lib/python3.9/site-packages/deepspeed/runtime/pipe/__init__.py", line 3, in <module>
    from .module import PipelineModule, LayerSpec, TiedLayerSpec
  File "/anaconda/envs/gist/lib/python3.9/site-packages/deepspeed/runtime/pipe/module.py", line 16, in <module>
    from ..activation_checkpointing import checkpointing
  File "/anaconda/envs/gist/lib/python3.9/site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 25, in <module>
    from deepspeed.runtime.config import DeepSpeedConfig
  File "/anaconda/envs/gist/lib/python3.9/site-packages/deepspeed/runtime/config.py", line 30, in <module>
    from ..monitor.config import get_monitor_config
  File "/anaconda/envs/gist/lib/python3.9/site-packages/deepspeed/monitor/config.py", line 70, in <module>
    class DeepSpeedMonitorConfig(DeepSpeedConfigModel):
  File "/anaconda/envs/gist/lib/python3.9/site-packages/deepspeed/monitor/config.py", line 82, in DeepSpeedMonitorConfig
    def check_enabled(cls, values):
  File "/anaconda/envs/gist/lib/python3.9/site-packages/pydantic/deprecated/class_validators.py", line 222, in root_validator
    return root_validator()(*__args)  # type: ignore
  File "/anaconda/envs/gist/lib/python3.9/site-packages/pydantic/deprecated/class_validators.py", line 228, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.4/u/root-validator-pre-skip

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/anaconda/envs/gist/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/anaconda/envs/gist/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/v-xincheng/projects/gisting/src/compress.py", line 9, in <module>
    from . import gist_llama, gist_t5, weight_diff
  File "/home/v-xincheng/projects/gisting/src/gist_llama.py", line 14, in <module>
    from transformers.models.llama import LlamaPreTrainedModel
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "/anaconda/envs/gist/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1116, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/anaconda/envs/gist/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1128, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.llama.modeling_llama because of the following error (look up to see its traceback):
If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.4/u/root-validator-pre-skip
```

**Comment by Hannibal046** [comment]
downgrading pydantic version solves the problem:
```
pip install pydantic==1.10.9
```

**Comment by siddharthganjoo** [comment]
May I ask what was the procedure to recover the base LLama model??
Im having a lot of troubles in getting the base weights and running the weight_diff.py script
