### ISSUE TITLE
having problems in creating k samples of the output

### ISSUE THREAD

**Issue by siddharthganjoo** [jayelm/gisting#22]
in the compress.py file

```
    generated_tokens = model.generate(
        max_new_tokens=max_new_tokens,
        num_return_sequences=3,  # Fixed to generate 3 samples
        do_sample=True,
        **gen_kwargs,
    )
```
    
    i am changing do sample to true but this is the error im facing
    
```
    Loading model /home/sganjoo/gisting/llama-7b
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:22<00:00,  7.65s/it]
Loading tokenizer
Compressing instruction
Decoding from model
Traceback (most recent call last):
  File "/home/sganjoo/.conda/envs/gisting/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/sganjoo/.conda/envs/gisting/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/sganjoo/gisting/src/compress.py", line 245, in <module>
    fire.Fire(main)
  File "/home/sganjoo/.conda/envs/gisting/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/sganjoo/.conda/envs/gisting/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/sganjoo/.conda/envs/gisting/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/sganjoo/.conda/envs/gisting/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/sganjoo/gisting/src/compress.py", line 197, in main
    generated_tokens = model.generate(
  File "/home/sganjoo/.conda/envs/gisting/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/sganjoo/.conda/envs/gisting/lib/python3.9/site-packages/transformers/generation/utils.py", line 1452, in generate
    return self.sample(
  File "/home/sganjoo/.conda/envs/gisting/lib/python3.9/site-packages/transformers/generation/utils.py", line 2468, in sample
    outputs = self(
  File "/home/sganjoo/.conda/envs/gisting/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sganjoo/gisting/src/gist_llama.py", line 797, in forward
    outputs = self.model(
  File "/home/sganjoo/.conda/envs/gisting/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sganjoo/gisting/src/gist_llama.py", line 583, in forward
    layer_outputs = decoder_layer(
  File "/home/sganjoo/.conda/envs/gisting/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sganjoo/gisting/src/gist_llama.py", line 315, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/sganjoo/.conda/envs/gisting/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sganjoo/gisting/src/gist_llama.py", line 212, in forward
    key_states = torch.cat([past_key_value[0], key_states], dim=2)
RuntimeError: Sizes of tensors must match except in dimension 2. Expected size 1 but got size 3 for tensor number 1 in the list.
```

**Comment by jayelm** [comment]
Hi, yeah, unfortunately I didn't end up testing/implementing batched decoding. There's likely a broadcasting error/bug somewhere in `gist_llama.py`, since you have to be a bit careful about the new gist attention masks when decoding in batches. I don't have bandwidth to fix this, but would welcome contributions!
